/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class rtrk_pnrs1_ra94_2013_projekat1_statisticsNative */

#ifndef _Included_rtrk_pnrs1_ra94_2013_projekat1_statisticsNative
#define _Included_rtrk_pnrs1_ra94_2013_projekat1_statisticsNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     rtrk_pnrs1_ra94_2013_projekat1_statisticsNative
 * Method:    getStatisticsResult
 * Signature: (II)F
 */
JNIEXPORT jfloat JNICALL Java_rtrk_pnrs1_ra94_12013_projekat1_statisticsNative_getStatisticsResult
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
